title: Suzanne Papik
logo: PXL_20240810_171931277.jpeg
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: dark
favicon: true


plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/smpapik
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: www.linkedin.com/in/suzanne-papik-6958a9125
  - name: This Repository
    icon: <i class="fa-brands fa-bookmark"></i>
    link: https://github.com/smpapik/smpapik.github.io


